### ISSUE TITLE
Prototype naar HTML

### ISSUE THREAD

**Issue by Lutrian1** [Lutrian1/the-client-website#6]
Sitemap 1(Fout)
![Image](https://github.com/user-attachments/assets/722d4a7e-b5c0-440d-9bf2-c7cb515f7d08)
Feedback hierop:
![Image](https://github.com/user-attachments/assets/4aeaed72-8d2f-4ed1-b7f7-ba99c86874fb)

Nieuwe sitemap
![Image](https://github.com/user-attachments/assets/7d183352-0f7e-489e-a4ee-e25a2a096fee)
Wireframe / Breakdown schets
![Image](https://github.com/user-attachments/assets/f1e2421f-0d21-47fe-b155-b4f069f84b69)
![Image](https://github.com/user-attachments/assets/9349d790-d6ce-4896-a240-3900c675dad3)
![Image](https://github.com/user-attachments/assets/31d9a575-2606-4f13-844d-0b9ce79d914b)

**Comment by sebas-hagoort** [comment]
je main page heet geen index.html. je zou de <body> tag 1 naar rechts kunnen zetten. Geen errors. Verder is het prima. Er kan nog meer content bij

**Comment by Sidopjescherm** [comment]
Er is geen error in je code. Ik zie niks met de validator

**Comment by Kerem-Tutucu** [comment]
Suleyman en ik hebben het in een validator gezet. We hebben geen error gekregen.

**Comment by Lutrian1** [comment]
Charley: in de breakdown schets, vertel ook de font size hoe groot de image zou worden etc
